name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'+

      - name: Install dependencies
        run: npm install

      - name: Run static file generation script
        run: node generate-static-files.js
      
      - name: Run sitemap generation script
        run: node generate-sitemap.js

      - name: Build static site
        run: npm run build  # If you have a build step for your static site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path-to-your-build-output
