name: Run Node.js and Bash Scripts, then Commit to Another Branch


on:
  push:
    branches:
      - source-code

jobs:
  run-scripts-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git user info
        run: |
          git config --global user.name "palash90"
          git config --global user.email "palash.kanti.kundu.90@gmail.com"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files before running the script
        run: |
          ls

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Node.js script
        run: |
          node ./generate-static-files.js  # Adjust the path to your Node.js script
      
      - name: Show files after running the script
        run: |
          ls

      - name: Checkout target branch
        run: |
          git fetch origin  # Ensure all branches are available
          git checkout -b main
      
      - name: Show files after checking out
        run: |
          ls

      - name: Commit changes to target branch
        run: |
          git add --all
      
      - name: Show changes made to the branch
        run: |
          git status

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "Run file generation"
          git push --set-upstream origin main
          

